// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCDPNeighbors(arg1) {
  return window['go']['wails_interfaces']['WailsInterface']['GetCDPNeighbors'](arg1);
}

export function GetIPInterface(arg1) {
  return window['go']['wails_interfaces']['WailsInterface']['GetIPInterface'](arg1);
}

export function GetStatus(arg1) {
  return window['go']['wails_interfaces']['WailsInterface']['GetStatus'](arg1);
}

export function GetVLAN(arg1) {
  return window['go']['wails_interfaces']['WailsInterface']['GetVLAN'](arg1);
}
