// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetCDPNeighbors():Promise<string>;

export function GetIPInterface():Promise<string>;

export function GetStatus():Promise<string>;

export function GetVLAN():Promise<string>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
