// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCDPNeighbors() {
  return window['go']['wails_interfaces']['WailsInterface']['GetCDPNeighbors']();
}

export function Startup(arg1) {
  return window['go']['wails_interfaces']['WailsInterface']['Startup'](arg1);
}
