// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCDPNeighbors(arg1:string):Promise<string>;

export function GetIPInterface(arg1:string):Promise<string>;

export function GetStatus(arg1:string):Promise<string>;

export function GetVLAN(arg1:string):Promise<string>;
